// Sistema visivo condiviso: palette colori, stili dei componenti e CSS globale


const palette = { bg: "#1c1712", panel: "#2a231b", panelAlt: "#241d16", parchment: "#ece2c8", parchmentDim: "#c9bd9d", garnet: "#9a3324", garnetBright: "#c2452f", gold: "#c8992f", line: "#4a3f30", successGreen: "#4c8c4a", dangerRed: "#a13b2e", neutralBlue: "#4a6f8a" };
const globalCss = `* { box-sizing: border-box; } input, select, textarea, button { font-family: inherit; } ::selection { background: ${palette.garnet}; color: ${palette.parchment}; } input[type=number] { -moz-appearance: textfield; text-align: center; } input[type=number]::-webkit-outer-spin-button, input[type=number]::-webkit-inner-spin-button { -webkit-appearance: none; margin: 0; } input[type=date] { color-scheme: dark; }`;

const styles = {
  app: { minHeight: "100vh", background: `radial-gradient(ellipse at top, #241d16 0%, ${palette.bg} 60%)`, color: palette.parchment, fontFamily: "'Iowan Old Style', 'Palatino Linotype', Georgia, serif", paddingBottom: 60 },
  header: { borderBottom: `2px solid ${palette.line}`, background: palette.panelAlt, position: "sticky", top: 0, zIndex: 10 },
  headerInner: { display: "flex", alignItems: "center", gap: 10, padding: "16px 24px 6px" },
  brandGlyph: { color: palette.gold, fontSize: 22 },
  brandTitle: { margin: 0, fontSize: 22, letterSpacing: "0.04em", fontWeight: 700, color: palette.parchment },
  tabs: { display: "flex", gap: 4, padding: "0 20px", overflowX: "auto" },
  tabBtn: { background: "transparent", border: "none", color: palette.parchmentDim, padding: "10px 16px", fontSize: 14.5, cursor: "grab", borderBottom: "3px solid transparent", fontFamily: "inherit", whiteSpace: "nowrap" },
  tabBtnActive: { color: palette.gold, borderBottom: `3px solid ${palette.garnetBright}` },
  tabBtnDragging: { opacity: 0.4 },
  main: { maxWidth: 1180, margin: "0 auto", padding: "24px 20px" },
  schedeLayout: { display: "grid", gridTemplateColumns: "220px 1fr", gap: 20, alignItems: "start" },
  sidebar: { background: palette.panel, border: `1px solid ${palette.line}`, borderRadius: 8, padding: 12, position: "sticky", top: 110 },
  sidebarTitle: { fontSize: 12, textTransform: "uppercase", letterSpacing: "0.08em", color: palette.parchmentDim, marginBottom: 8 },
  pgListItem: { display: "flex", alignItems: "center", borderRadius: 6, marginBottom: 4 },
  pgListItemActive: { background: "rgba(154,51,36,0.25)" },
  pgListBtn: { flex: 1, textAlign: "left", background: "transparent", border: "none", color: palette.parchment, padding: "8px 8px", cursor: "pointer", display: "flex", flexDirection: "column" },
  pgListName: { fontSize: 14.5 }, pgListSub: { fontSize: 11.5, color: palette.parchmentDim },
  pgDelBtn: { background: "transparent", border: "none", color: palette.garnetBright, cursor: "pointer", padding: "0 8px", width: 26, textAlign: "center", flexShrink: 0 },
  invSpacer: { width: 26, flexShrink: 0 },
  newPgBtn: { width: "100%", marginTop: 8, background: "transparent", border: `1px dashed ${palette.line}`, color: palette.gold, borderRadius: 6, padding: "8px 0", cursor: "pointer", fontSize: 13.5 },
  sheet: { background: palette.panel, border: `1px solid ${palette.line}`, borderRadius: 10, padding: 22 },
  sheetTopRow: { display: "flex", flexWrap: "wrap", gap: 16, alignItems: "flex-end", borderBottom: `1px solid ${palette.line}`, paddingBottom: 16, marginBottom: 16 },
  nameInput: { flex: "1 1 260px", background: "transparent", border: "none", borderBottom: `2px solid ${palette.garnet}`, color: palette.parchment, fontSize: 26, fontWeight: 700, padding: "4px 2px", fontFamily: "inherit" },
  sheetTopFields: { display: "flex", gap: 12, flexWrap: "wrap" },
  miniField: { display: "flex", flexDirection: "column", fontSize: 11.5, color: palette.parchmentDim, gap: 3 },
  miniInput: { background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "5px 8px", fontSize: 14, minWidth: 90 },
  threeColGrid: { display: "grid", gridTemplateColumns: "1fr 1fr auto 1fr 1fr", columnGap: 8, rowGap: 8, alignItems: "start", marginBottom: 14 },
  fiveColGrid: { display: "grid", gridTemplateColumns: "1fr 1fr auto 1fr 1fr", columnGap: 8, rowGap: 8, alignItems: "start", marginBottom: 14 },
  additionalClassGrid: { display: "grid", gridTemplateColumns: "1fr 1fr auto auto", columnGap: 8, alignItems: "start", marginBottom: 12 },
  columnTitle: { fontSize: 13, textTransform: "uppercase", letterSpacing: "0.07em", color: palette.gold, fontWeight: 700, marginBottom: 8, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, textAlign: "center", width: "100%" },
  columnTitleLeft: { fontSize: 13, textTransform: "uppercase", letterSpacing: "0.07em", color: palette.gold, fontWeight: 700, marginTop: 14, marginBottom: 6 },
  pairRow: { display: "flex", gap: 8 },
  gridInput: { width: "100%", background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "5px 8px", fontSize: 14 },
  levelInput: { width: 64, textAlign: "center", background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "5px 8px", fontSize: 14 },
  classeRow: { display: "flex", flexWrap: "wrap", gap: 10, alignItems: "flex-end", marginBottom: 8 },
  derivedRow: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 10, marginBottom: 16, marginTop: 14 },
  statBox: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "10px 12px", textAlign: "center" },
  statBoxLabel: { fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.06em", color: palette.parchmentDim },
  statBoxValue: { fontSize: 26, color: palette.gold, fontWeight: 700, lineHeight: 1.2 },
  statBoxSub: { fontSize: 10, color: palette.parchmentDim }, statBoxExtra: { marginTop: 4 },
  smallNumInput: { width: 60, background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 4, padding: "2px 4px", fontSize: 12, textAlign: "center" },
  checkField: { display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: palette.parchmentDim },
  sectionLabel: { fontSize: 13, textTransform: "uppercase", letterSpacing: "0.07em", color: palette.gold, margin: "22px 0 8px", paddingTop: 16, borderTop: `1px solid ${palette.line}`, fontWeight: 700, display: "flex", alignItems: "center", gap: 10 },
  sectionDivider: { borderTop: `1px solid ${palette.line}`, margin: "22px 0 0" },
  abilityGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(90px, 1fr))", gap: 10, marginBottom: 8 },
  abilityCard: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "10px 6px", textAlign: "center" },
  abilityName: { fontSize: 10.5, color: palette.parchmentDim, marginBottom: 4 },
  abilityScoreInput: { width: 46, textAlign: "center", background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, fontSize: 16, padding: "2px 0" },
  abilityModRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 6, marginTop: 4 },
  abilityMod: { fontSize: 14, color: palette.gold, fontWeight: 700 },
  twoCol: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 },
  checkRow: { display: "flex", alignItems: "center", gap: 6, padding: "3px 0", fontSize: 13 },
  skillHeaderRow: { display: "flex", alignItems: "center", gap: 6, padding: "0 0 4px", fontSize: 9.5, color: palette.parchmentDim, textTransform: "uppercase", letterSpacing: "0.03em" },
  skillHeaderFlag: { width: 26, textAlign: "center" },
  checkboxGroup: { display: "flex", gap: 16 },
  checkboxCol: { width: 26, display: "flex", justifyContent: "center" },
  dragHandle: { cursor: "grab", color: palette.parchmentDim, fontSize: 13, width: 14 },
  checkRowLabel: { flex: 1 }, checkRowVal: { color: palette.gold, fontWeight: 700, minWidth: 36, textAlign: "right", whiteSpace: "nowrap" },
  checkRowValInput: { color: palette.gold, fontWeight: 700, width: 40, textAlign: "center", background: "transparent", border: `1px solid transparent`, borderRadius: 4, padding: "2px 0" },
  checkRowValOverride: { border: `1px solid ${palette.gold}`, background: palette.panel },
  resetOverrideBtn: { background: "transparent", border: "none", color: palette.parchmentDim, cursor: "pointer", fontSize: 13, padding: "0 2px" },
  abTag: { color: palette.parchmentDim, fontStyle: "normal", fontSize: 11 },
  hint: { fontSize: 11.5, color: palette.parchmentDim, lineHeight: 1.5 },
  diceBtn: { background: "transparent", border: `1px solid ${palette.line}`, borderRadius: 5, cursor: "pointer", fontSize: 13, padding: "1px 6px", color: palette.parchmentDim },
  chipRow: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 6 },
  chip: { background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchmentDim, borderRadius: 999, padding: "5px 12px", fontSize: 12.5, cursor: "pointer" },
  chipActive: { background: palette.garnet, color: palette.parchment, borderColor: palette.garnetBright },
  searchInput: { width: "100%", background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 6, padding: "9px 12px", fontSize: 13.5, marginBottom: 4 },
  pgSelectorRow: { display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center", marginBottom: 10 },
  pgSelect: { flex: "2 1 220px", background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 6, padding: "8px 10px", fontSize: 13.5 },
  roundBar: { display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center", marginBottom: 16, padding: "10px 12px", background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8 },
  roundLabel: { fontSize: 16, fontWeight: 700, color: palette.gold, marginRight: 10 },
  combattenteAttivo: { borderColor: palette.gold, boxShadow: `0 0 0 1px ${palette.gold}` },
  turnoIndicatore: { color: palette.gold, fontSize: 18, fontWeight: 700 },
  condizioniRow: { display: "flex", flexWrap: "wrap", gap: 6, margin: "6px 0" },
  condizioneChip: { background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchmentDim, borderRadius: 999, padding: "3px 10px", fontSize: 11.5, cursor: "pointer" },
  condizioneChipAttiva: { background: palette.garnet, borderColor: palette.garnetBright, color: palette.parchment, fontWeight: 700 },
  risultatoIncontroBox: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "14px 16px", textAlign: "center" },
  difficoltaGrande: { fontSize: 24, fontWeight: 700, marginTop: 6 },
  difficoltaFacile: { color: palette.successGreen },
  difficoltaMedia: { color: palette.gold },
  difficoltaDifficile: { color: palette.garnetBright },
  difficoltaMortale: { color: palette.dangerRed },
  searchResults: { border: `1px solid ${palette.line}`, borderRadius: 6, overflow: "hidden", marginTop: 4 },
  searchResultRow: { width: "100%", display: "flex", justifyContent: "space-between", background: palette.panelAlt, border: "none", borderBottom: `1px solid ${palette.line}`, color: palette.parchment, padding: "8px 12px", fontSize: 13, cursor: "pointer", fontFamily: "inherit" },
  itemList: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 8 },
  itemRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 10, background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "8px 12px" },
  itemGroup: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "8px 12px", display: "flex", flexDirection: "column", gap: 6 },
  itemNoteInput: { width: "100%", background: "transparent", border: "none", borderTop: `1px dashed ${palette.line}`, color: palette.parchmentDim, fontSize: 12.5, fontStyle: "italic", padding: "6px 0 0", resize: "none" },
  overrideRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  overrideLabel: { fontSize: 11, color: palette.parchmentDim, fontStyle: "italic" },
  overrideInput: { background: palette.panel, border: `1px solid ${palette.line}`, borderRadius: 5, color: palette.parchment, fontSize: 12, padding: "3px 6px", minWidth: 140 },
  componenteDannoBlocco: { marginBottom: 10, paddingBottom: 8, borderBottom: `1px dashed ${palette.line}` },
  componenteDannoTipo: { color: palette.gold, fontWeight: 700, fontSize: 13, marginBottom: 4, textTransform: "capitalize" },
  itemCard: { display: "flex", flexDirection: "column", gap: 8, background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "8px 12px" },
  itemSubRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 10 },
  dadiTitle: { fontSize: 13, textTransform: "uppercase", letterSpacing: "0.07em", color: palette.parchment, fontWeight: 700 },
  removeX: { background: "transparent", border: "none", color: palette.garnetBright, fontSize: 15, cursor: "pointer", padding: "0 4px", flexShrink: 0 },
  itemName: { background: "transparent", border: "none", color: palette.gold, fontWeight: 700, fontSize: 14, cursor: "pointer", padding: 0, fontFamily: "inherit" },
  itemActions: { marginLeft: "auto", display: "flex", gap: 10, flexWrap: "wrap" },
  magicSelect: { width: 110, background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "4px 8px", fontSize: 12 },
  modLabel: { display: "flex", flexDirection: "row", alignItems: "center", fontSize: 10.5, color: palette.parchmentDim, textTransform: "uppercase", gap: 6, whiteSpace: "nowrap" },
  modInput: { width: 50, background: palette.panel, border: `1px solid ${palette.line}`, color: palette.gold, fontWeight: 700, borderRadius: 5, padding: "3px 4px", fontSize: 12.5, textAlign: "center" },
  invTable: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 8 },
  invRow: { display: "flex", gap: 8, alignItems: "flex-start" },
  invNome: { flex: "2 1 160px", background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "6px 10px", fontSize: 13.5 },
  invQty: { width: 64, background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "6px 8px", fontSize: 13.5, textAlign: "center" },
  moneyCatInput: { flex: "1 1 120px", background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "6px 10px", fontSize: 13.5 },
  moneyNumLabel: { width: 84, textAlign: "center" },
  slotTwoColLayout: { display: "flex", gap: 16, alignItems: "flex-start", marginBottom: 6 },
  slotGrid: { display: "flex", flexWrap: "wrap", alignItems: "flex-start", gap: 10, flex: 1 },
  slotGridRows: { display: "flex", flexDirection: "column", gap: 10, flex: 1 },
  slotStregDivider: { borderLeft: `1px dashed ${palette.line}`, paddingLeft: 16, display: "flex", gap: 16, alignItems: "flex-start" },
  slotCol: { display: "flex", flexDirection: "column", alignItems: "center", gap: 6, background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "10px 8px", width: 78 },
  slotColTitle: { fontSize: 11, textTransform: "uppercase", letterSpacing: "0.04em", color: palette.gold, fontWeight: 700, textAlign: "center" },
  preparatiValore: { fontSize: 22, fontWeight: 700, color: palette.parchment, textAlign: "center", padding: "4px 0" },
  slotEmptyHint: { fontSize: 11, color: palette.parchmentDim },
  slotTotaliInput: { width: 42, height: 42, borderRadius: "50%", textAlign: "center", background: palette.panel, border: `2px solid ${palette.line}`, color: palette.parchment, fontSize: 16, fontWeight: 700 },
  slotCheckRow: { display: "flex", flexWrap: "wrap", gap: 4, justifyContent: "center", maxWidth: 70 },
  slotCheckbox: { width: 16, height: 16, border: `1px solid ${palette.line}`, borderRadius: 3, background: palette.panel, cursor: "pointer", padding: 0 },
  slotCheckboxUsed: { background: palette.garnet, borderColor: palette.garnetBright },
  moneyNum: { width: 84, background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "6px 8px", fontSize: 13.5, textAlign: "center" },
  moneyNumGold: { width: 84, background: palette.panelAlt, border: `1px solid ${palette.gold}`, color: palette.gold, fontWeight: 700, borderRadius: 5, padding: "6px 8px", fontSize: 13.5, textAlign: "center" },
  invPos: { flex: "1 1 140px", background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "6px 10px", fontSize: 13.5 },
  tableHeaderCell: { background: "transparent", border: "none", color: palette.gold, fontSize: 11, textTransform: "uppercase", letterSpacing: "0.06em", fontWeight: 700, padding: "0 10px" },
  notes: { width: "100%", minHeight: 90, background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 8, padding: 10, fontSize: 13.5, fontFamily: "inherit", resize: "vertical" },
  panel: { background: palette.panel, border: `1px solid ${palette.line}`, borderRadius: 10, padding: 24 },
  panelTitle: { marginTop: 0, marginBottom: 0, color: palette.gold, fontSize: 22 },
  equipHeadRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 28, marginBottom: 4 },
  accordionItem: { borderBottom: `1px solid ${palette.line}` },
  accordionHead: { width: "100%", display: "flex", justifyContent: "space-between", background: "transparent", border: "none", color: palette.parchment, padding: "12px 4px", fontSize: 15, cursor: "pointer", fontFamily: "inherit" },
  accordionBody: { padding: "0 4px 14px", color: palette.parchmentDim, fontSize: 13.5, lineHeight: 1.6 },
  ruleTableWrap: { overflowX: "auto", marginBottom: 10 },
  ruleTable: { width: "100%", borderCollapse: "collapse", fontSize: 12.5 },
  ruleTh: { textAlign: "left", padding: "6px 8px", borderBottom: `2px solid ${palette.garnet}`, color: palette.gold, fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.04em", whiteSpace: "nowrap" },
  ruleTd: { padding: "5px 8px", borderBottom: `1px solid ${palette.line}`, color: palette.parchment },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(230px, 1fr))", gap: 12, marginBottom: 18 },
  cardGrid4: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, marginBottom: 18 },
  dataCard: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: 14 },
  dataCardClickable: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: 14, cursor: "pointer", textAlign: "left", fontFamily: "inherit", width: "100%" },
  dataCardTitleBtn: { color: palette.gold, fontWeight: 700, marginBottom: 4, fontSize: 15, background: "transparent", border: "none", padding: 0, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  dataCardTitleStatic: { color: palette.gold, fontWeight: 700, marginBottom: 4, fontSize: 15 },
  dataCardBody: { fontSize: 13, color: palette.parchment, lineHeight: 1.5, marginTop: 6 },
  cardBtnRow: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 8 },
  subRow: { display: "flex", justifyContent: "space-between", alignItems: "center", borderTop: `1px dashed ${palette.line}`, padding: "4px 0" },
  smallBtn: { background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "4px 10px", fontSize: 11.5, cursor: "pointer" },
  smallBtnActive: { background: palette.garnet, borderColor: palette.garnetBright, color: palette.parchment },
  smallDangerBtn: { background: "transparent", border: `1px solid ${palette.garnet}`, color: palette.garnetBright, borderRadius: 5, padding: "4px 10px", fontSize: 11.5, cursor: "pointer" },
  formBox: { background: palette.panelAlt, border: `1px dashed ${palette.line}`, borderRadius: 8, padding: 16, marginTop: 8 },
  formRow: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 8, alignItems: "center" },
  formInput: { flex: "1 1 140px", background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "7px 10px", fontSize: 13.5 },
  formTextarea: { width: "100%", minHeight: 60, background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "8px 10px", fontSize: 13, fontFamily: "inherit", marginBottom: 8, resize: "vertical" },
  primaryBtn: { background: palette.garnet, border: "none", color: palette.parchment, borderRadius: 6, padding: "8px 18px", fontSize: 13.5, cursor: "pointer", fontWeight: 700 },
  primaryBtnDisabled: { background: palette.line, color: palette.parchmentDim, cursor: "not-allowed" },
  overlay: { position: "fixed", inset: 0, background: "rgba(10,8,6,0.72)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 16 },
  modalBox: { background: palette.panel, border: `1px solid ${palette.line}`, borderRadius: 12, padding: 24, maxWidth: 520, width: "100%", maxHeight: "85vh", overflowY: "auto", position: "relative" },
  modalBoxWide: { background: palette.panel, border: `1px solid ${palette.line}`, borderRadius: 12, padding: 24, maxWidth: 920, width: "100%", maxHeight: "90vh", overflowY: "auto", position: "relative" },
  noteToolbar: { display: "flex", alignItems: "center", gap: 8, marginBottom: 8, flexWrap: "wrap" },
  noteToolBtn: { background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "5px 12px", fontSize: 13, cursor: "pointer" },
  noteColorBtn: { width: 22, height: 22, borderRadius: "50%", border: `1px solid ${palette.line}`, cursor: "pointer", padding: 0 },
  noteEditorBox: { minHeight: 320, background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: 14, color: palette.parchment, fontSize: 14, lineHeight: 1.6, outline: "none" },
  pdfFrame: { width: "100%", height: "75vh", border: `1px solid ${palette.line}`, borderRadius: 8, background: "#fff", marginTop: 10 },
  smallBtnLink: { background: palette.panel, border: `1px solid ${palette.line}`, color: palette.gold, borderRadius: 5, padding: "6px 12px", fontSize: 12.5, textDecoration: "none", display: "inline-block" },
  txtViewer: { whiteSpace: "pre-wrap", wordBreak: "break-word", fontFamily: "inherit", fontSize: 13.5, lineHeight: 1.6, color: palette.parchment, maxHeight: "75vh", overflowY: "auto", background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: 14 },
  mapToolbar: { display: "flex", alignItems: "center", gap: 8, margin: "12px 0", flexWrap: "wrap" },
  mapContainer: { overflow: "auto", border: `1px solid ${palette.line}`, borderRadius: 8, background: palette.panelAlt, height: "60vh", marginTop: 8 },
  mapInner: { position: "relative", display: "inline-block", transformOrigin: "0 0" },
  mapImg: { display: "block", maxWidth: "none" },
  mapMarker: { position: "absolute", transform: "translate(-50%, -50%)", cursor: "pointer", fontSize: 22, filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.8))" },
  markerEditPanel: { display: "flex", gap: 8, alignItems: "center", marginTop: 10, flexWrap: "wrap", background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: 10 },
  mapThumb: { width: "100%", height: 120, objectFit: "cover", borderRadius: 6, marginBottom: 8, cursor: "pointer", border: `1px solid ${palette.line}` },
  identityImage: { maxWidth: 280, maxHeight: 340, width: "100%", objectFit: "cover", borderRadius: 8, border: `1px solid ${palette.line}`, marginBottom: 8, display: "block" },
  identityFieldsRow: { display: "flex", flexWrap: "wrap", gap: 16, marginBottom: 8 },
  mapTitleInput: { width: "100%", background: "transparent", border: "none", borderBottom: `1px dashed ${palette.line}`, color: palette.gold, fontWeight: 700, fontSize: 15, padding: "2px 0", marginBottom: 4, fontFamily: "inherit" },
  modalClose: { position: "absolute", top: 12, right: 12, background: "transparent", border: "none", color: palette.parchmentDim, fontSize: 16, cursor: "pointer" },
  modalTitle: { margin: "0 0 6px", color: palette.gold, fontSize: 20, paddingRight: 24 },
  modalDesc: { fontSize: 13.5, lineHeight: 1.6, marginTop: 14 },
  detailGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 14 },
  detailField: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 6, padding: "6px 10px" },
  detailFieldLabel: { fontSize: 10, textTransform: "uppercase", color: palette.parchmentDim, letterSpacing: "0.05em" },
  detailFieldValue: { fontSize: 13.5, marginTop: 2 },
  modeRow: { display: "flex", gap: 8, margin: "12px 0" },
  modeBtn: { flex: 1, background: palette.panelAlt, border: `1px solid ${palette.line}`, color: palette.parchmentDim, borderRadius: 6, padding: "8px 0", fontSize: 13, cursor: "pointer" },
  modeBtnActive: (m) => ({ background: m === "vantaggio" ? palette.successGreen : m === "svantaggio" ? palette.dangerRed : palette.neutralBlue, color: "#fff", borderColor: "transparent" }),
  diceRow: { display: "flex", gap: 12, justifyContent: "center", margin: "16px 0", minHeight: 56, alignItems: "center", flexWrap: "wrap" },
  die: { width: 56, height: 56, borderRadius: 10, border: "2px solid", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, fontWeight: 700 },
  resultBox: { textAlign: "center", marginBottom: 10 },
  critText: { color: palette.gold, fontWeight: 700, fontSize: 14, marginBottom: 4 },
  failText: { color: "#8a8171", fontWeight: 700, fontSize: 14, marginBottom: 4 },
  totalText: { fontSize: 20, fontWeight: 700, color: palette.parchment },
  hpGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 10, marginBottom: 4 },
  hpGrid2: { display: "flex", gap: 8, marginTop: 8 },
  hpBox: { background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "10px 12px", display: "flex", flexDirection: "column", gap: 6, alignItems: "center" },
  dadiVitaRow: { display: "flex", alignItems: "center", gap: 6, fontSize: 12.5 },
  dadiVitaLabel: { color: palette.gold, fontWeight: 700, width: 24 },
  dadiVitaInput: { width: 44, textAlign: "center", background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "3px 4px", fontSize: 13 },
  dadiVitaTot: { color: palette.parchmentDim, fontSize: 11.5 },
  hpBoxLabel: { fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.05em", color: palette.parchmentDim },
  hpBoxInput: { width: "100%", textAlign: "center", background: palette.panel, border: `1px solid ${palette.line}`, color: palette.gold, fontWeight: 700, borderRadius: 5, fontSize: 20, padding: "4px 0" },
  hpBoxSmallInput: { width: "100%", textAlign: "center", background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, fontSize: 12, padding: "4px 2px" },
  abilitaExtraRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", background: palette.panelAlt, border: `1px solid ${palette.line}`, borderRadius: 8, padding: "8px 12px" },
  traitTitle: { color: palette.gold, fontWeight: 700, fontSize: 14.5 },
  traitTitleInput: { color: palette.gold, fontWeight: 700, fontSize: 14.5, background: "transparent", border: "none", borderBottom: `1px dashed transparent`, width: "100%", padding: "1px 0" },
  traitDescInput: { color: palette.parchmentDim, fontSize: 12.5, background: "transparent", border: "none", width: "100%", resize: "none", padding: "2px 0", fontFamily: "inherit" },
  traitSource: { display: "inline-block", color: palette.parchmentDim, fontSize: 10.5, border: `1px solid ${palette.line}`, borderRadius: 999, padding: "1px 10px", margin: "3px 0" },
  applicaASelect: { flex: "0 0 150px", background: palette.panel, border: `1px solid ${palette.line}`, color: palette.parchment, borderRadius: 5, padding: "7px 8px", fontSize: 12.5 },
};

export { palette, styles, globalCss };
